### ISSUE TITLE
Comment

### ISSUE THREAD

**Issue by richdouglasevans** [yatesco/reasonml-handbook-gitbook#1]
The code block in [Functors - huh!?](https://coliny.gitbooks.io/reasonml-developer-handbook/functions-huh.html) has a malformed comment: too much Clojure :wink: 

```clojure
;; this is the container full of 'String's
```

It should be:

```java
// this is the container full of 'String's
```

You _could_ correct it but consider deleting the comment entirely: it doesn't add anything to the code block and you explain it in prose English in the subsequent paragraph anyway.

You might also want to consider using idiomatic Java that reflects the way folk generally would initialize such a list these days: this keeps the focus on your point about "a container of things" rather than the awkward way one might initialize such a container in the Java of old.

```java
List<String> myStrings = List.of("hi", "there");
```

> , or rather it will be when gitbook stops refusing the integrate!

:smile: Yes, I would've raised PR for something so minor but there's nothing to raise the PR against.

I have more comments about the content rather than just mention of a typo but I'll let you crack on and finish up.

Go go go Colin :rocket:

**Comment by yatesco** [comment]
@richdouglasevans - great to hear from you! Thanks for the comments - yes to all of them :-). Thanks bud!
